export const SET_MENU_PRODUCTS = "SET_MENU_PRODUCTS";
export const SET_MENU_CATEGORIES = "SET_MENU_CATEGORIES";
export const CHANGE_ACTIVE_LINK = "CHANGE_ACTIVE_LINK";
export const FILTER_PRODUCTS_WITH_CATEGORY_ID =
  "FILTER_PRODUCTS_WITH_CATEGORY_ID";

export const ADD_CART_PRODUCT = "ADD_CART_PRODUCT";
