export const SET_MENU_PRODUCTS = "SET_MENU_PRODUCTS";
export const SET_MENU_CATEGORIES = "SET_MENU_CATEGORIES";
export const CHANGE_ACTIVE_LINK = "CHANGE_ACTIVE_LINK";
export const FILTER_PRODUCTS_WITH_CATEGORY_ID =
  "FILTER_PRODUCTS_WITH_CATEGORY_ID";

export const ADD_CART_PRODUCT = "ADD_CART_PRODUCT";
export const REMOVE_CART_PRODUCT = "REMOVE_CART_PRODUCT";
export const SET_CART_PRODUCTS = "SET_CART_PRODUCTS";
export const SAVE_CART = "SAVE_CART";
export const UPDATE_CART = "UPDATE_CART";
export const SET_USER_INFO = "SET_USER_INFO";
export const USER_REGISTER = "USER_REGISTER";
export const USER_AUNTHENTICATE = "USER_AUNTHENTICATE";
export const UPDATE_USER = "UPDATE_USER;";
export const USER_LOG_OUT = "USER_LOG_OUT";
export const CREATE_ORDER = "CREATE_ORDER";

export const SET_ORDERS = "SET_ORDERS";
